"""empty message

Revision ID: 2b34c00497a2
Revises: 5d99102c6643
Create Date: 2019-01-18 11:00:48.573961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b34c00497a2'
down_revision = '5d99102c6643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('admin', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group', 'artist', ['admin'], ['id'])
    op.add_column('posts', sa.Column('post_group', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'artist', ['post_author'], ['id'])
    op.create_foreign_key(None, 'posts', 'group', ['post_group'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'group', ['post_author'], ['id'])
    op.drop_column('posts', 'post_group')
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'admin')
    # ### end Alembic commands ###
