"""empty message

Revision ID: 2e17c6f5faec
Revises: 82be71f2b3bc
Create Date: 2019-01-06 23:30:18.754659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e17c6f5faec'
down_revision = '82be71f2b3bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'last_seen')
    # ### end Alembic commands ###
