"""empty message

Revision ID: 5e4a363c7ad3
Revises: 712866a12144
Create Date: 2019-01-11 21:48:17.709825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4a363c7ad3'
down_revision = '712866a12144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventName', sa.String(length=60), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('eventDescription', sa.String(length=100), nullable=True),
    sa.Column('isFree', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eventName')
    )
    op.create_table('members',
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], )
    )
    op.drop_table('member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'group_id')
    )
    op.drop_table('members')
    op.drop_table('events')
    # ### end Alembic commands ###
