"""empty message

Revision ID: 712866a12144
Revises: 2e17c6f5faec
Create Date: 2019-01-11 16:30:14.489122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712866a12144'
down_revision = '2e17c6f5faec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    # ### end Alembic commands ###
