"""empty message

Revision ID: 82be71f2b3bc
Revises: b482ffe6da23
Create Date: 2019-01-06 22:16:54.528628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82be71f2b3bc'
down_revision = 'b482ffe6da23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('aboutMe', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'aboutMe')
    # ### end Alembic commands ###
