"""fresh start

Revision ID: 8b9f82f5ef72
Revises: 
Create Date: 2019-01-19 14:33:50.235955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9f82f5ef72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('aboutMe', sa.String(length=300), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_email'), 'artist', ['email'], unique=True)
    op.create_index(op.f('ix_artist_username'), 'artist', ['username'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventName', sa.String(length=60), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('eventDescription', sa.String(length=100), nullable=True),
    sa.Column('isFree', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('event_author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_author'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eventName')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupName', sa.String(length=140), nullable=True),
    sa.Column('groupDescription', sa.String(length=140), nullable=True),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], )
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('post_group', sa.Integer(), nullable=True),
    sa.Column('post_author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_author'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['post_group'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('members')
    op.drop_table('group')
    op.drop_table('events')
    op.drop_index(op.f('ix_artist_username'), table_name='artist')
    op.drop_index(op.f('ix_artist_email'), table_name='artist')
    op.drop_table('artist')
    # ### end Alembic commands ###
